plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "D:\\Escritorio\\10 SKILLS ADRI Y JUANPE\\kit-instagram-web\\clientes\\pira.restaurante"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]